### PR TITLE
Edited some line breaks in the readme file

### PR DESCRIPTION
**Pull request by 23Yc8z**

### CODE REVIEW

**Comment by ryanxcharles** [comment]
there is something wrong with your PR. there are no changes to merge.

Screen Shot 2019-12-18 at 11 05 34 AM

**Comment by 23Yc8z** [comment]
I made and saved the changes... I'm having a hard time learning github...

**Comment by ryanxcharles** [comment]
Looks to me like you created a file and then deleted it, leading to a net change of 0.

**Comment by ryanxcharles** [comment]
i'm closing this because it doesn't make any changes. please redo the PR with the changes you intend to make.

**Pull request closed without merging**
