### PR TITLE
Add full transactions to PaymentDetails.

### PR DESCRIPTION
**Pull request by KarlTheProgrammer**
This is my proposal for adding full transaction support to BIP-0270. It allows merchants to specify inputs  as well as more complex transaction structures that will be required for Tokenized to work with this protocol. The added complexity should be minimal as any software using this protocol is already serializing the bitcoin P2P transaction structure.

The main reason this is needed is so that merchants have the option of adding signatures to the transaction for meta data, or evidence of approval of payment.

### CODE REVIEW

**Comment by Siko91** [comment]
I thought about this proposal a bit.
It seems the idea is that it gives more flexibility not only because the requester can specify a few inputs, but also because 
> Many complex negotiations can be built on top of this

I see these complex negotiations as a problem.
Because they are complex.
I believe that the only way to achieve close to 100% adoption is to make it simple and straightforward to implement. That means that the implementation should have almost **no conditional logic**. No special negotiation types. No "If that input is present, then I sign in this slightly different way".

This proposal is great exactly because of the simplicity for the wallets. They just do one thing in one way and now they can unlock ALL transaction types.

I am against the idea of many complex negotiation types in a single protocol.
It is ok to have a separate protocol for them.

That being said, if you still want to add inputs, there might be ways to do that without the wallet needing to care about it (by simply making it possible for the server to add these inputs **After** it receives the payment transaction). This however would require to change the current protocol in a few places. For example, wallets will no longer be allowed to broadcast a TX by themselves.
How does that sound?

**Comment by Siko91** [comment]
> The server can't add inputs after the client signs it unless the client signs it with something other than SIGHASH_ALL, which would be much more complex than what is suggested.

True. This would add a different type of complexity.

But this protocol is named "Simplified Payments Protocol". It feels wrong to include complex negotiation types while also using that name.

I don't know what exactly your use case will be, but since it is about tokens, I am assuming that not any input will be appropriate and Token wallets will have to select special token inputs.
(I don't know how Tokenized works yet, So I'm just guessing.)

I know that this is not a great argumet but the protocol wouldn't fit the title.

**Comment by Siko91** [comment]
On the other hand, I think I see how adding inputs before the wallets gets the transaction, that would allow for swaps if the input somehow represents a token instead of Bitcoins.

> "I will give you this input of 50 USD but it is signed in a way that is only valid if you add enough intputs to satisfy my prepared output of 50 USD worth of Bitcoin."

Is this what you have in mind?
(Again - no idea how tokenized actually works)

If scenarios like this would become possible it might be worth the extra bit of complexity.
Can you give some example scenarios, please.

**Comment by KarlTheProgrammer** [comment]
> But this protocol is named "Simplified Payments Protocol". It feels wrong to include complex negotiation types while also using that name.

Maybe this is what most people currently want. I was trying to bring most use cases under one protocol. If most people want a protocol that only does simple BSV transfers, then we will design a different protocol for the rest of use cases.

> I am assuming that not any input will be appropriate and Token wallets

Tokenized isn't linked to UTXOs, just "addresses". So specific inputs aren't required. They just have to meet the criteria (basically have required signatures). I haven't designed the user negotiation for tokens yet, but a simple token send probably doesn't require the receiver to provide an input. Atomic swaps in which a token is being exchanged for BSV or another token would require the receiver to specify an input.

> Can you give some example scenarios, please.

The main general scenarios are:
- Transactions in which the parties want on chain proof of approval by both parties.
- Transactions in which the receiver wants on chain proof of approval.
- Transactions in which something is being exchanged.

I believe these scenarios will be very common. More common than simple BSV transfers. We know for a fact that merchants want on chain information tied to payments. It is currently preventing them from accepting payments. Without a merchant signature, that data can be spammed.

**Comment by Siko91** [comment]
> - Transactions in which the parties want on chain proof of approval by both parties.
> - Transactions in which the receiver wants on chain proof of approval.

If the purpose is to provide onchain approval, then a more flexible way will be to provide an extra output message where (in op_return) the merchant signs a message saying that he approves the exact list of outputs that he approves.

Inputs won't be as flexible, because (since the transaction is incomplete both in inputs and outputs) they can't possible use SIGHASH ALL. Some outputs (that they disagree with) can be added.

> - Transactions in which something is being exchanged.

This is the interesting one. Here SIGHASH SINGLE can be very powerful (if I understand the idea properly)
I am worried that if inputs are the norm, then some wallets might take them, but not output in the proper format, because they didn't understand the inputs. Depending on the token protocol, they might end up destroying the tokens (as can happen with colored coins, I think) or making an invalid token transaction  that doesn't move the tokens at all.
If all wallets accept inputs by default, then many of them will end up not checking what the inputs actually mean and what outputs are expected for them.

There are multiple ways to solve that problem, but I believe the most elegant will be through the "network" value. Requests that are related to a specific second layer protocol (like tokens) can simply add the protocol name after the network name.

```js
"bitcoin" // for regular payments
```
```js
"bitcoin+tokenized" // for transactions related to tokenized
```
and so on...

This way, any specific use case can be an extension on top of this protocol, can have it's own rules of what is valid and (if needed) it can also add extra data to the payment request (like inputs).

**Comment by Siko91** [comment]
@KarlTheProgrammer , @ryanxcharles 

Since this discussion ended I discovered some very valid use cases for including inputs in the BIP-270 transactions.
However I believe that we do not need to modify BIP270 itself, in order to make it support the requests of specific inputs. It can happen in a much less intrusive way.

I wrote this : https://github.com/BitcoinSofia/BIP-276/blob/master/bip-0276.mediawiki

Please review it and help me finish it.

**Comment by KarlTheProgrammer** [comment]
I am not sure how to comment on that document, so I will comment here. 

I think the format of the input string still needs to be specified. An input is a 32 byte tx id, 4 byte output index, variable length script, and a 4 byte sequence ID. Are you suggesting using bitcoin input encoding and converting to hex?

Also, I think many scenarios will require SIGHASH_ALL. The "server" can include unsigned inputs, the "client" can add outputs and signed inputs, then the "server" can approve by signing their inputs and transmitting the transaction to the network. SIGHASH_ALL provides the benefit of the transaction not being modifiable by either party after any signature is added, except of course adding signatures.

**Comment by Siko91** [comment]
SIGHASH_ALL is not an option because the wallet will need to add an additional output, in order to give itself the leftover change from its own inputs.

The other document is unfinished. The best way to contribute is to send a pull request with an idea.
I have not specified how the inputs should be included, because I don't know yet. I am still undecided on that.
You are welcome to help. :)

**Comment by Siko91** [comment]
I made some updates to the document. Please read it again @KarlTheProgrammer 

(The new version also extends this BIP, but that would only be valid if my [newest pull request](https://github.com/moneybutton/bips/pull/16#issue-323292974) gets approved.)

**Comment by KarlTheProgrammer** [comment]
When SIGHASH_ALL is used, the inputs provided by the merchant will not be signed (sigScript will be empty). The consumer will have to add inputs and outputs, then sign their inputs. When they pass the tx back to the merchant, the merchant can sign their inputs to approve the tx and make it valid.

**Comment by Siko91** [comment]
That can work, yes.

But let's stop chatting here.
This is off-topic.
You can open pull requests, or just send me emails at aleks@bitcoinsofia.com

**Comment by Siko91** [comment]
I updated the document as per your proposal. Thank you.
I temporarily moved the document to a private repository.
I want to speak to some people before I finish it.. ;)

**Pull request closed without merging**
